tagapp/config/routes.rb
Rails.application.routes.draw do
  resources :displaydata

end

tagapp/app/models/displaydatum.rb
class Displaydatum < ActiveRecord::Base
end

tagapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

tagapp/app/controllers/displaydata_controller.rb
class DisplaydataController < ApplicationController
  before_action :set_displaydatum, only: [:show, :edit, :update, :destroy]

  # GET /displaydata
  # GET /displaydata.json
  def index
    @displaydata = Displaydatum.all
  end

  # GET /displaydata/1
  # GET /displaydata/1.json
  def show
  end

  # GET /displaydata/new
  def new
    @displaydatum = Displaydatum.new
  end

  # GET /displaydata/1/edit
  def edit
  end

  # POST /displaydata
  # POST /displaydata.json
  def create
    @displaydatum = Displaydatum.new(displaydatum_params)

    respond_to do |format|
      if @displaydatum.save
        format.html { redirect_to @displaydatum, notice: 'Displaydatum was successfully created.' }
        format.json { render :show, status: :created, location: @displaydatum }
      else
        format.html { render :new }
        format.json { render json: @displaydatum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /displaydata/1
  # PATCH/PUT /displaydata/1.json
  def update
    respond_to do |format|
      if @displaydatum.update(displaydatum_params)
        format.html { redirect_to @displaydatum, notice: 'Displaydatum was successfully updated.' }
        format.json { render :show, status: :ok, location: @displaydatum }
      else
        format.html { render :edit }
        format.json { render json: @displaydatum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /displaydata/1
  # DELETE /displaydata/1.json
  def destroy
    @displaydatum.destroy
    respond_to do |format|
      format.html { redirect_to displaydata_url, notice: 'Displaydatum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_displaydatum
      @displaydatum = Displaydatum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def displaydatum_params
      params.require(:displaydatum).permit(:infodate, :hour, :positive, :neutral, :negative, :cloud, :image_loc)
    end
end

tagapp/app/helpers/application_helper.rb
module ApplicationHelper
end

tagapp/app/helpers/displaydata_helper.rb
module DisplaydataHelper
end

tagapp/app/views/displaydata/_form.html.erb
<%= form_for(@displaydatum) do |f| %>
  <% if @displaydatum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@displaydatum.errors.count, "error") %> prohibited this displaydatum from being saved:</h2>

      <ul>
      <% @displaydatum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :infodate %><br>
    <%= f.date_select :infodate %>
  </div>
  <div class="field">
    <%= f.label :hour %><br>
    <%= f.number_field :hour %>
  </div>
  <div class="field">
    <%= f.label :positive %><br>
    <%= f.number_field :positive %>
  </div>
  <div class="field">
    <%= f.label :neutral %><br>
    <%= f.number_field :neutral %>
  </div>
  <div class="field">
    <%= f.label :negative %><br>
    <%= f.number_field :negative %>
  </div>
  <div class="field">
    <%= f.label :cloud %><br>
    <%= f.text_field :cloud %>
  </div>
  <div class="field">
    <%= f.label :image_loc %><br>
    <%= f.text_field :image_loc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

tagapp/app/views/displaydata/edit.html.erb
<h1>Editing Displaydatum</h1>

<%= render 'form' %>

<%= link_to 'Show', @displaydatum %> |
<%= link_to 'Back', displaydata_path %>

tagapp/app/views/displaydata/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Available Word Clouds</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Infodate</th>
      <th>Hour</th>
      <th>Positive</th>
      <th>Neutral</th>
      <th>Negative</th>
      <th>Cloud</th>
      <th>Image loc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @displaydata.each do |displaydatum| %>
      <tr>
        <td><%= displaydatum.infodate %></td>
        <td><%= displaydatum.hour %></td>
        <td><%= displaydatum.positive %></td>
        <td><%= displaydatum.neutral %></td>
        <td><%= displaydatum.negative %></td>
        <td><%= displaydatum.cloud %></td>
        <td><%= displaydatum.image_loc %></td>
        <td><%= link_to 'Show', displaydatum %></td>
        <td><%= link_to 'Edit', edit_displaydatum_path(displaydatum) %></td>
        <td><%= link_to 'Destroy', displaydatum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

tagapp/app/views/displaydata/new.html.erb
<h1>New Displaydatum</h1>

<%= render 'form' %>

<%= link_to 'Back', displaydata_path %>

tagapp/app/views/displaydata/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Infodate:</strong>
  <%= @displaydatum.infodate %>
</p>

<p>
  <strong>Hour:</strong>
  <%= @displaydatum.hour %>
</p>

<p>
  <strong>Image loc:</strong>
  <%= @displaydatum.image_loc %>
</p>


<%= image_tag @displaydatum.image_loc , :class => "img_preview" %>
<p>

<%= link_to 'Edit', edit_displaydatum_path(@displaydatum) %> |
<%= link_to 'Back', displaydata_path %>

tagapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tagapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" <%= link_to 'DVLA SocialApp', displaydata_path  %> </a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
<!--        <li class="active"><a href="#">Home</a></li>
        <li><a href="#about">About</a></li>
        <li><a href="#contact">Contact</a></li>  -->
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>
<div class='container-fluid'>
  <div class='span12'><%= yield %></div>
</div>


</body>
</html>